#!/usr/bin/env bash
# Installing Nginx

apt-get update
apt-get install -y nginx

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

kill -s HUP $(cat /var/run/nginx.pid)

echo "<html><body>Hello World!</body></html>" > /var/www/html/index.html


service nginx start
