#!/bin/bash

# Update package lists
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Create a configuration file for redirection
sudo bash -c 'cat > /etc/nginx/sites-available/redirect_me' << EOF
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://twitter.com/OussamaRami;
    }
}
EOF

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

sudo nginx -t

sudo systemctl reload nginx

